### PR TITLE
feat: cross-repository saving

### PR DESCRIPTION
**Pull request by Necromos**
Changes:
* feat: cross-repository saving changes
  * introduced `persistance-repository` as optional parameter
  * introduced `PERSISTANCE_GITHUB_TOKEN` as optional ENV variable
  * introduced `repoName` to saved CLA record for clarity
  * code should use persistance github token and save CLA acceptance
    into `persistance-repository`
  * aded README related to changes
* fix: changed casing of `path-To-cladocument` to `path-to-cla-document`
* fix: fixed issue graphQL handling

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@Necromos the plan with this fork is to, keep our changes small and always stay rebased to the upstream repo at `cla-assistant/github-action`.

Could you amend the above commit to be a little more descriptive - mentions that it customizes for ockam and adds persistence in a git repo

**Comment by Necromos** [comment]
@mrinalwadhwa Amended. 1 note tho, I was thinking about splitting it up into separate PRs but that would need to be synchronized somehow as main.js would need to have the latest changes from master.

This could be mitigated by i.e.:
- releases/tags will be used and main.js will be built when new release/tag will be released
- some automatic tool running build will be introduced

As well, same problem with main.js will occur when upstream of original repository will be kept on PRs that will be introduced into this repository.

**Comment by mrinalwadhwa** [comment]
@Necromos I like the idea of an automated build of `main.js` maybe with an azure pipeline or a different github action.   

Our changes that are rebased on top of upstream can delete the upstream main.js

**Comment by Necromos** [comment]
@mrinalwadhwa rebased locally into cla repo (see https://github.com/ockam-network/cla-action/pull/1/commits/c2a880e055aa34ca3305c3f14bf3a69cdc620698), shall I be squashing their changes to keep up with your approach or do you want them to exist?

**Comment by Necromos** [comment]
@mrinalwadhwa bump: https://github.com/ockam-network/cla-action/pull/1#issuecomment-635834012 :)

**Comment by Necromos** [comment]
@mrinalwadhwa I'm closing this one and I will open up many smaller ones to fit naming convention

**Pull request closed without merging**
