### PR TITLE
chore: adding action.yml inputs definitions

### PR DESCRIPTION
**Pull request by Necromos**
Adding missing definitions for action inputs

### CODE REVIEW

**Comment by Necromos** [comment]
recheckcla

**Comment by Necromos** [comment]
recheckcla

**Comment by Necromos** [comment]
recheckcla

**Comment by Necromos** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mrinalwadhwa** [comment]
recheckcla

**Comment by mrinalwadhwa** [comment]
rebased and merged https://github.com/ockam-network/cla-action/commit/c74f4dcfff7e380b2cbddcfa6555dea9c6275a49

**Pull request closed without merging**
